### ISSUE TITLE
build-treeview..issue with domains that start with D.

### ISSUE THREAD

**Issue by danSpotter** [ITMicaH/Powershell-functions#2]
$DomainName = (($domaindn -split 'DC=' | ? { $_ }) -join '.') -replace ','

**Comment by ITMicaH** [comment]
Another great catch Dan!! Thank you! I've chosen to correct the isssue like this:

`$DomainName = $DomainDN.Replace(',DC=','.').Substring(3)`

I think that's a little easier on the eyes, but you're solution works as well.
