### ISSUE TITLE
Your code is under what license?

### ISSUE THREAD

**Issue by obilodeau** [ITMicaH/Powershell-functions#3]
I want to include your network connection profile setter into [malboxes](https://github.com/GoSecure/malboxes) but I need to know if I can.

This site can help choosing a license if you are unsure which you should pick: https://choosealicense.com/

Not having an explicit license makes the condition of use fall back into copyright law which defaults to exclusive copyrights which would prohibit me to use your code. See https://choosealicense.com/no-license/.

If you are not opinionated about it, pick the MIT License which is simple to understand and permissive.

**Comment by ITMicaH** [comment]
Hi. I've added a MIT license to the script so have fun with it. Sorry for the late reaction.

**Comment by TealAlex** [comment]
Sorry to revive this. We would like to use your contact script https://github.com/ITMicaH/Powershell-functions/tree/master/Office/Outlook in a script we would like to release under the MIT license. Could you add a license file there as well?
