### ISSUE TITLE
Crendtial error when run as local administrator

### ISSUE THREAD

**Issue by Blank-Vcf** [ITMicaH/Powershell-functions#4]
I use your since a while to move computer in AD after sysprep. I discover your fastest new version but since build 1703 in windows sysprep changes i need to run the powershell script as local admin. Even if i push Domain and credential value i get this error (sorry it's in french):
```
Exception lors de l'appel de «GetCurrentForest» avec «0» argument(s): «Le contexte de sécurité actuel n'est pas associé à un domaine ou une forêt Active Directory.»
Au caractère C:\Users\Administrateur\Desktop\org.ps1:655 : 4
+             $forest = [System.DirectoryServices.ActiveDirectory.Forest]::GetCurrentForest ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ActiveDirectoryOperationException
 
```

ir seems that we can solve it bu replacing the line 655 with:
`$forest = Get-ADforest $Domain -Credential $Credential`
and move it after line:
` $root = New-Object -TypeName System.DirectoryServices.DirectoryEntry("LDAP://$DomainDN",$Credential.UserName,$Credential.GetNetworkCredential().password)
				   `

output of Get-ADforest seems  the same as [System.DirectoryServices.ActiveDirectory.Forest]::GetCurrentForest() but it wreck the rest of the script in the Build-TreeView function

**Comment by ITMicaH** [comment]
Strange. I'm on Win10 1709 and I don't experience any such issues, whether I run the function as Admin or not. Then again, I'm not running the script after a sysprep. I'd have to check to see the ramifications of that. Can you tell me more about how and when you run the function? Like this:

1. Sysprep
2. Reboot
3. Join domain
4. Run script

**Comment by ITMicaH** [comment]
Closing the issue due to lack of response.
